using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Heco.Common.Models;
using Heco.Common.Enums;
using Heco.Common.Interfaces;
using Heco.Common.Services.Settings;

namespace Heco.Common.Services.Profiles;

/// <summary>
///   Manages application profiles — fingerprints to match connections to profiles,
///   special built-in profiles, and per-profile rule overrides.
/// </summary>
public interface IProfileManager
{
    /// <summary>All profiles (built-in special + user-defined + auto-generated).</summary>
    ObservableCollection<Profile> Profiles { get; }

    /// <summary>Event raised when profiles are modified.</summary>
    event EventHandler<ProfileEventArgs> ProfileChanged;

    /// <summary>Match a connection entry to a profile.</summary>
    Profile? MatchConnection(ConnectionEntry connection);

    /// <summary>Match process info to a profile by PID.</summary>
    Profile? MatchProcess(uint pid);

    /// <summary>Auto-generate a profile for an unknown process.</summary>
    Profile AutoGenerate(uint pid);

    /// <summary>Add or update a profile.</summary>
    void SaveProfile(Profile profile);

    /// <summary>Delete a profile by name.</summary>
    bool DeleteProfile(string name);

    /// <summary>Load profiles from the settings service.</summary>
    void LoadProfiles();

    /// <summary>Save all profiles to the settings service.</summary>
    void SaveProfiles();
}

/// <summary>
///   EventArgs for profile change events.
/// </summary>
public sealed class ProfileEventArgs : EventArgs
{
    public Profile Profile { get; }
    public ProfileChangeType ChangeType { get; }

    public ProfileEventArgs(Profile profile, ProfileChangeType changeType)
    {
        Profile = profile;
        ChangeType = changeType;
    }
}

public enum ProfileChangeType
{
    Added,
    Modified,
    Deleted
}

/// <summary>
///   A profile representing a process or group of processes.
/// </summary>
public sealed class Profile
{
    /// <summary>Display name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Whether this is a built-in special profile (system, unknown, loopback).</summary>
    public bool IsSpecial { get; set; }

    /// <summary>Whether this profile was auto-generated.</summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>Fingerprints used to match processes to this profile.</summary>
    public List<ProfileFingerprint> Fingerprints { get; set; } = new();

    /// <summary>Per-profile network action override (null = inherit from global).</summary>
    public NetworkActionSettings? ActionOverride { get; set; }

    /// <summary>Per-profile blocklist configuration.</summary>
    public BlocklistsSettings? Blocklists { get; set; }

    /// <summary>When this profile was created.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>How many times this profile has been matched.</summary>
    public long HitCount { get; set; }

    public override string ToString() => Name;
}
