using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Text.RegularExpressions;
using Heco.Common.Models;
using Heco.Common.Enums;
using Heco.Common.Interfaces;
using Heco.Common.Services.Process;
using Heco.Common.Services.Settings;
using Heco.Common.Services.Diagnostics;
using Heco.Common.Services.Profiles;

namespace Heco.Common.Services.Profiles;

/// <summary>
///   Manages application profiles — fingerprint matching, auto-generation,
///   special built-in profiles, and per-profile rule override chain.
/// </summary>
public sealed class ProfileManager : IProfileManager
{
    private readonly IProcessMonitor _processMonitor;
    private readonly ISettingsService _settingsService;
    private readonly ObservableCollection<Profile> _profiles = new();

    public ObservableCollection<Profile> Profiles => _profiles;
    public event EventHandler<ProfileEventArgs>? ProfileChanged;

    public ProfileManager(IProcessMonitor processMonitor, ISettingsService settingsService)
    {
        _processMonitor = processMonitor;
        _settingsService = settingsService;
    }

    //  Matching 

    public Profile? MatchConnection(ConnectionEntry connection)
    {
        return MatchProcess(connection.ProcessId);
    }

    public Profile? MatchProcess(uint pid)
    {
        try
        {
            // 1. Special profiles: check by PID first
            var special = _profiles.FirstOrDefault(p => p.IsSpecial);
            if (special is not null && IsSystemProcess(pid))
                return special;

            // 2. Get process info for fingerprint matching
            var processInfo = _processMonitor.GetProcessInfo(pid);
            if (processInfo is null)
                return _profiles.FirstOrDefault(p => p.Name == "Unknown");

            // 3. Non-auto profiles first (user-defined), then auto-generated
            var candidates = _profiles
                .Where(p => !p.IsSpecial && p.Fingerprints.Count > 0)
                .OrderBy(p => p.IsAutoGenerated)
                .ThenBy(p => p.Name);

            foreach (var profile in candidates)
            {
                if (MatchesProfile(profile, processInfo))
                {
                    profile.HitCount++;
                    return profile;
                }
            }

            // 4. No match found — return Unknown
            return _profiles.FirstOrDefault(p => p.Name == "Unknown");
        }
        catch (Exception ex)
        {
            Logger.Debug($"MatchProcess({pid}): {ex.Message}");
            return _profiles.FirstOrDefault(p => p.Name == "Unknown");
        }
    }

    public Profile AutoGenerate(uint pid)
    {
        var processInfo = _processMonitor.GetProcessInfo(pid);
        if (processInfo is null)
            return _profiles.FirstOrDefault(p => p.Name == "Unknown")!;

        var profile = CreateDefaultProfile(processInfo);
        _profiles.Add(profile);
        ProfileChanged?.Invoke(this, new ProfileEventArgs(profile, ProfileChangeType.Added));
        SaveProfiles();
        return profile;
    }

    //  CRUD ─

    public void SaveProfile(Profile profile)
    {
        var existing = _profiles.FirstOrDefault(p =>
            string.Equals(p.Name, profile.Name, StringComparison.OrdinalIgnoreCase));

        if (existing is not null)
        {
            var idx = _profiles.IndexOf(existing);
            _profiles[idx] = profile;
            ProfileChanged?.Invoke(this, new ProfileEventArgs(profile, ProfileChangeType.Modified));
        }
        else
        {
            _profiles.Add(profile);
            ProfileChanged?.Invoke(this, new ProfileEventArgs(profile, ProfileChangeType.Added));
        }

        SaveProfiles();
    }

    public bool DeleteProfile(string name)
    {
        var profile = _profiles.FirstOrDefault(p =>
            string.Equals(p.Name, name, StringComparison.OrdinalIgnoreCase));

        if (profile is null || profile.IsSpecial)
            return false;

        _profiles.Remove(profile);
        ProfileChanged?.Invoke(this, new ProfileEventArgs(profile, ProfileChangeType.Deleted));
        SaveProfiles();
        return true;
    }

    //  Persistence ─

    public void LoadProfiles()
    {
        _profiles.Clear();
        EnsureSpecialProfiles();

        if (_settingsService.ProfileSettings.Profiles is { } profileList)
        {
            foreach (var sp in profileList)
            {
                _profiles.Add(new Profile
                {
                    Name = sp.Name,
                    IsAutoGenerated = sp.IsAutoGenerated,
                    Fingerprints = sp.Fingerprints,
                    ActionOverride = sp.ActionOverride,
                    Blocklists = sp.Blocklists
                });
            }
        }

        Logger.Info($"Loaded {_profiles.Count} profiles");
    }

    public void SaveProfiles()
    {
        _settingsService.ProfileSettings.Profiles = _profiles
            .Where(p => !p.IsSpecial)
            .Select(p => new SettingsProfile
            {
                Name = p.Name,
                IsAutoGenerated = p.IsAutoGenerated,
                Fingerprints = p.Fingerprints,
                ActionOverride = p.ActionOverride,
                Blocklists = p.Blocklists
            })
            .ToList();

        _settingsService.Save();
    }

    //  Special profiles 

    private void EnsureSpecialProfiles()
    {
        // Built-in special profiles always exist
        var specials = new[]
        {
            new Profile
            {
                Name = "System",
                IsSpecial = true,
                Fingerprints = new List<ProfileFingerprint>
                {
                    new() { Type = FingerprintType.ProcessName, Operator = MatchOperator.Equals, Value = "System" }
                },
                ActionOverride = new NetworkActionSettings
                {
                    AllowOutbound = true,
                    AllowInbound = true
                }
            },
            new Profile
            {
                Name = "Unknown",
                IsSpecial = true,
                Fingerprints = new List<ProfileFingerprint>(),
                ActionOverride = null
            },
            new Profile
            {
                Name = "Loopback",
                IsSpecial = true,
                ActionOverride = new NetworkActionSettings
                {
                    AllowOutbound = true,
                    AllowInbound = true
                }
            }
        };

        foreach (var special in specials)
        {
            if (!_profiles.Any(p => string.Equals(p.Name, special.Name, StringComparison.OrdinalIgnoreCase)))
                _profiles.Add(special);
        }
    }

    //  Helpers 

    private static bool IsSystemProcess(uint pid)
    {
        return pid is 0 or 4;
    }

    private bool MatchesProfile(Profile profile, ProcessInfo processInfo)
    {
        if (profile.Fingerprints.Count == 0)
            return false;

        return profile.Fingerprints.All(fp => FpMatches(fp, processInfo));
    }

    private static bool FpMatches(ProfileFingerprint fp, ProcessInfo info)
    {
        var value = fp.Type switch
        {
            FingerprintType.FullPath => info.ExecutablePath,
            FingerprintType.ProcessName => info.ProcessName,
            FingerprintType.CommandLine => info.CommandLine,
            FingerprintType.WindowsService => info.ServiceName,
            FingerprintType.WindowsStore => info.PackageFamilyName,
            _ => null
        };

        if (value is null) return false;

        // Apply operator
        return fp.Operator switch
        {
            MatchOperator.Equals => string.Equals(value, fp.Value, StringComparison.OrdinalIgnoreCase),
            MatchOperator.StartsWith => value.StartsWith(fp.Value, StringComparison.OrdinalIgnoreCase),
            MatchOperator.Contains => value.IndexOf(fp.Value, StringComparison.OrdinalIgnoreCase) >= 0,
            MatchOperator.Wildcard => MatchWildcard(value, fp.Value),
            MatchOperator.Regex => Regex.IsMatch(value, fp.Value, RegexOptions.IgnoreCase),
            _ => false
        };
    }

    private static bool MatchWildcard(string input, string pattern)
    {
        // Simple wildcard: * matches any sequence, ? matches single char
        var regex = "^" + Regex.Escape(pattern)
            .Replace("\\*", ".*")
            .Replace("\\?", ".") + "$";
        return Regex.IsMatch(input, regex, RegexOptions.IgnoreCase);
    }

    private static Profile CreateDefaultProfile(ProcessInfo processInfo)
    {
        var profile = new Profile
        {
            Name = CleanProfileName(processInfo.ProcessName),
            IsAutoGenerated = true,
            CreatedAt = DateTime.UtcNow
        };

        // Primary: FullPath fingerprint
        if (processInfo.ExecutablePath is not null)
        {
            profile.Fingerprints.Add(new ProfileFingerprint
            {
                Type = FingerprintType.FullPath,
                Operator = MatchOperator.Equals,
                Value = processInfo.ExecutablePath
            });
        }

        // Secondary: ProcessName fingerprint
        profile.Fingerprints.Add(new ProfileFingerprint
        {
            Type = FingerprintType.ProcessName,
            Operator = MatchOperator.Equals,
            Value = processInfo.ProcessName
        });

        // If service, add service name fingerprint
        if (processInfo.IsService && processInfo.ServiceName is not null)
        {
            profile.Fingerprints.Add(new ProfileFingerprint
            {
                Type = FingerprintType.WindowsService,
                Operator = MatchOperator.Equals,
                Value = processInfo.ServiceName
            });
        }

        return profile;
    }

    private static string CleanProfileName(string processName)
    {
        // Remove .exe extension, capitalize first letter
        var name = processName;
        if (name.EndsWith(".exe", StringComparison.OrdinalIgnoreCase))
            name = name.Substring(0, name.Length - 4);

        if (name.Length > 0)
            name = char.ToUpper(name[0]) + name.Substring(1);

        return name;
    }
}
