using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Windows;
using System.Windows.Input;
using Heco.Common.Enums;
using Heco.Common.Services.Profiles;
using Heco.Common.Services.Settings;
using Heco_Firewall.Helpers;
using Heco_Firewall.Windows;

namespace Heco_Firewall.ViewModels;

/// <summary>
///   ViewModel for the Application Profiles page.
///   Manages per-application network policies (allow/block outbound/inbound).
/// </summary>
internal sealed class ProfilesViewModel : ObservableObject
{
    private readonly IProfileManager _profileManager;
    private Profile? _selectedProfile;
    private string _searchText = string.Empty;
    private string _statusText = string.Empty;

    public ProfilesViewModel(IProfileManager profileManager)
    {
        _profileManager = profileManager;

        EditProfileCommand = new RelayCommand(_ => BeginEdit(), _ => SelectedProfile != null);
        DeleteProfileCommand = new RelayCommand(_ => DeleteProfile(), _ => SelectedProfile != null && !SelectedProfile.IsSpecial);
        AutoGenerateCommand = new RelayCommand(_ => AutoGenerate());
        RefreshCommand = new RelayCommand(_ => Refresh());

        Refresh();
    }

    //  Properties 

    public ObservableCollection<Profile> Profiles => _profileManager.Profiles;

    public Profile? SelectedProfile
    {
        get => _selectedProfile;
        set
        {
            if (SetProperty(ref _selectedProfile, value))
                CommandManager.InvalidateRequerySuggested();
        }
    }

    public string SearchText
    {
        get => _searchText;
        set
        {
            if (SetProperty(ref _searchText, value))
                Refresh();
        }
    }

    public string StatusText
    {
        get => _statusText;
        set => SetProperty(ref _statusText, value);
    }

    public int TotalProfiles => Profiles.Count;
    public int AutoGeneratedCount => Profiles.Count(p => p.IsAutoGenerated);
    public int SpecialCount => Profiles.Count(p => p.IsSpecial);
    public long TotalHits => Profiles.Sum(p => p.HitCount);

    //  Commands 

    public ICommand EditProfileCommand { get; }
    public ICommand DeleteProfileCommand { get; }
    public ICommand AutoGenerateCommand { get; }
    public ICommand RefreshCommand { get; }

    //  Methods ─

    /// <summary>Reload all profiles from disk and update stats.</summary>
    public void Refresh()
    {
        _profileManager.LoadProfiles();
        UpdateStatus();
        OnPropertyChanged(nameof(TotalProfiles));
        OnPropertyChanged(nameof(AutoGeneratedCount));
        OnPropertyChanged(nameof(SpecialCount));
        OnPropertyChanged(nameof(TotalHits));
    }

    /// <summary>Open the profile edit window for the currently selected profile.</summary>
    private void BeginEdit()
    {
        if (SelectedProfile == null) return;

        var window = new ProfileEditWindow(_profileManager, SelectedProfile)
        {
            Owner = Application.Current.MainWindow
        };

        if (window.ShowDialog() == true)
        {
            SelectedProfile = null;
            Refresh();
        }
    }

    /// <summary>Auto-generate profiles from currently running processes.</summary>
    private void AutoGenerate()
    {
        try
        {
            var processes = System.Diagnostics.Process.GetProcesses()
                .Where(p =>
                {
                    try { _ = p.ProcessName; return true; }
                    catch { return false; }
                })
                .Select(p => p.ProcessName)
                .Distinct()
                .OrderBy(n => n)
                .ToList();

            var existingNames = new HashSet<string>(Profiles.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);
            var added = 0;

            foreach (var procName in processes)
            {
                if (existingNames.Contains(procName)) continue;

                var profile = new Profile
                {
                    Name = procName,
                    IsAutoGenerated = true,
                    Fingerprints = new List<ProfileFingerprint>
                    {
                        new()
                        {
                            Type = FingerprintType.ProcessName,
                            Operator = MatchOperator.Equals,
                            Value = procName
                        }
                    }
                };

                _profileManager.SaveProfile(profile);
                existingNames.Add(procName);
                added++;
            }

            Refresh();
            DialogWindow.ShowInfo($"Auto-generated {added} new profiles from running processes.", "Auto-Generate");
        }
        catch (Exception ex)
        {
            DialogWindow.ShowError($"Error during auto-generate: {ex.Message}", "Error");
        }
    }

    /// <summary>Delete the selected profile after user confirmation.</summary>
    private void DeleteProfile()
    {
        if (SelectedProfile == null || SelectedProfile.IsSpecial)
            return;

        var result = DialogWindow.ShowQuestion(
            $"Delete profile '{SelectedProfile.Name}'?",
            "Confirm Delete");

        if (result != DialogBoxResult.Yes) return;

        var name = SelectedProfile.Name;
        _profileManager.DeleteProfile(name);
        SelectedProfile = null;
        Refresh();
    }

    private void UpdateStatus()
    {
        StatusText = $"{Profiles.Count} profiles · {AutoGeneratedCount} auto · {TotalHits} total hits";
    }
}
