namespace Heco.WinDivert.Enums;

public enum StateType : int
{
    CLOSED, LISTEN, SYN_SENT, SYN_RECEIVED, ESTABLISHED,
    FIN_WAIT_1, FIN_WAIT_2, CLOSE_WAIT, CLOSING, LAST_ACK,
    TIME_WAIT, DELETE_TCB, UNKNOWN = -1,
}